# Generated by Django 3.0.4 on 2020-04-17 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wcow', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='plantacion',
            name='ancho_del_borde',
            field=models.DecimalField(decimal_places=3, default=1, max_digits=6),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='plantacion',
            name='distancia',
            field=models.DecimalField(decimal_places=3, default=1, max_digits=6),
            preserve_default=False,
        ),
    ]
